repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.15.7
  hooks:
    # Run the linter.
    - id: ruff-check
      types_or: [ python, pyi, jupyter, pyproject ]
    # Run the formatter.
    - id: ruff-format
      types_or: [ python, pyi, jupyter, pyproject ]
      args: [ --check ]
- repo: https://github.com/astral-sh/ty-pre-commit
  rev: v0.0.78
  hooks:
    - id: ty
